import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  item: {
    flexDirection: "row",
    width: "100%",
    padding: 10,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#F1F5F9",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  unavailableItem: {
    backgroundColor: "#F8F9FA",
    borderColor: "#E2E8F0",
    opacity: 0.7,
  },
  imageContainer: {
    marginRight: 16,
    position: "relative",
  },
  image: {
    width: 60,
    height: 70,
    borderRadius: 8,
    backgroundColor: "#f0f0f0",
  },
  unavailableImage: {
    opacity: 0.5,
  },
  placeholderImage: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#E5E7EB",
  },
  placeholderText: {
    fontSize: 12,
    color: "#999",
    fontWeight: "500",
  },
  unavailableOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  unavailableText: {
    color: "white",
    fontSize: 10,
    fontWeight: "bold",
  },
  productInfo: {
    flex: 1,
    flexDirection: "column",
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  nameAndPriceContainer: {
    flex: 1,
    marginLeft: -5,
  },
  nameRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  name: {
    fontWeight: "bold",
    fontSize: 14,
    color: "#1A202C",
    flex: 1,
  },
  unavailableName: {
    color: "#718096",
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
  },
  originalPrice: {
    fontSize: 13,
    color: "#718096",
    textDecorationLine: "line-through",
  },
  discountedPrice: {
    fontSize: 13,
    color: "#1a6d38ff",
    fontWeight: "600",
  },
  singlePrice: {
    fontSize: 13,
    color: "#24a352ff",
    fontWeight: "600",
    marginTop: 4,
  },
  controlsContainer: {
    alignItems: "flex-end",
  },
  quantityControls: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 6,
    backgroundColor: "#fff",
  },
  quantityButton: {
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  quantityText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#374151",
    minWidth: 20,
    textAlign: "center",
  },
  editButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF2F0",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#f14343",
    marginTop: 8,
  },
  editButtonText: {
    color: "#f14343",
    fontSize: 12,
    fontWeight: "500",
    marginLeft: 4,
  },
  unavailableLabel: {
    fontSize: 12,
    color: "#E53E3E",
    fontWeight: "500",
    marginBottom: 4,
  },
  customizationsContainer: {
    paddingVertical: 3,
  },
  customizationsLabel: {
    fontSize: 12,
    color: "#4A5568",
    fontWeight: "600",
    marginBottom: 2,
  },
  customizationText: {
    fontSize: 11,
    color: "#718096",
    lineHeight: 14,
  },
  dietBox: {
    width: 14,
    height: 14,
    borderWidth: 1.5,
    borderRadius: 2,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
  },
  dietDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
});