import { Dimensions, StyleSheet } from "react-native";
const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  card: {
    backgroundColor: "#fff",
    marginHorizontal: 8,
    marginBottom: 16,
    borderRadius: 12,
    padding: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  storeInfo: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  storeImage: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: "#f0f0f0",
  },
  storeDetails: {
    flex: 1,
    marginLeft: 12,
  },
  storeName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    marginBottom: 4,
  },
  storeMetrics: {
    fontSize: 12,
    color: "#666",
  },
  visitStoreButton: {
    backgroundColor: "#f5f5f5",
    padding: 8,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  productsCarousel: {
    backgroundColor: "#f8f8f8",
    borderRadius: 12,
    padding: 8,
    marginTop: 4,
  },
  productsContainer: {
    paddingLeft: 4,
  },
  productCard: {
    width: width * 0.48,
    marginRight: 12,
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#eee",
    overflow: "hidden",
  },
  productImage: {
    width: "100%",
    height: 90,
    backgroundColor: "#f0f0f0",
  },
  productInfo: {
    paddingHorizontal: 8,
    paddingTop: 6,
    paddingBottom: 8,
    flex: 1,
    justifyContent: "flex-start",
  },
  nameRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  productName: {
    flex: 1,
    fontSize: 13,
    fontWeight: "500",
    color: "#333",
  },
  priceCartRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 6,
    marginRight: 4,
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  price: {
    fontSize: 11,
    fontWeight: "bold",
    color: "green",
  },
  unavailablePrice: {
    fontSize: 11,
    color: "#999",
    fontStyle: "italic",
  },
  originalPrice: {
    fontSize: 11,
    color: "#999",
    textDecorationLine: "line-through",
    marginLeft: 6,
    marginRight: 4,
  },
  productDiscountBadge: {
    position: "absolute",
    top: 8,
    left: 6,
    backgroundColor: "#2ecc71",
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 4,
    zIndex: 1,
  },
  productDiscountText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "700",
  },
  likeButtonContainer: {
    position: "absolute",
    top: 8,
    right: 8,
    zIndex: 2,
    backgroundColor: "rgba(255,255,255,0.9)",
    borderRadius: 20,
    padding: 6,
    elevation: 3,
  },
});