import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fbfcfd",
    paddingHorizontal: 10,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: "#4A5568",
    fontWeight: "500",
  },
  emptyText: {
    fontSize: 18,
    color: "#2D3748",
    fontWeight: "600",
    marginTop: 16,
    textAlign: "center",
  },
  emptySubText: {
    fontSize: 14,
    color: "#718096",
    marginTop: 8,
    textAlign: "center",
  },
  scrollContainer: {
    paddingHorizontal: 11,
    paddingVertical: 12,
  },
  storeCard: {
    backgroundColor: "#fcf3f3",
    borderRadius: 12,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#F1F5F9",
    overflow: "hidden",
  },
  deletingCard: {
    opacity: 0.6,
  },
  imageContainer: {
    position: "relative",
  },
  storeImage: {
    width: "100%",
    height: 140,
    backgroundColor: "#F7FAFC",
  },
  heartButton: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 34,
    height: 34,
    borderRadius: 77,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  offerBadgeContainer: {
    position: "absolute",
    top: 10,
    left: 10,
  },
  storeInfo: {
    padding: 6,
  },
  storeName: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1A202C",
    marginBottom: 6,
  },
  categories: {
    fontSize: 14,
    color: "#4A5568",
    marginBottom: 6,
    lineHeight: 18,
  },
  address: {
    fontSize: 13,
    color: "#718096",
    marginBottom: 12,
    lineHeight: 16,
  },
  statusContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  openStatus: {
    flexDirection: "row",
    alignItems: "center",
  },
  openDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#27b45b",
    marginRight: 6,
  },
  openText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#27b45b",
  },
  discountBadge: {
    backgroundColor: "#FFE4E6",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
  },
  discountText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#E53E3E",
  },
});