import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  section: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1a1a1a",
    marginBottom: 12,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  editBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    padding: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    backgroundColor: "white",
  },
  editText: {
    fontSize: 12,
    color: "#666",
    fontWeight: "500",
  },
  storeCard: {
    flexDirection: "row",
    backgroundColor: "white",
    padding: 16,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    alignItems: "center",
  },
  storeImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 12,
  },
  storeInfo: {
    flex: 1,
  },
  storeName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1a1a1a",
    marginBottom: 4,
  },
  storeAddress: {
    fontSize: 14,
    color: "#666",
  },
  addressCard: {
    backgroundColor: "white",
    padding: 16,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  addressName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1a1a1a",
    marginBottom: 4,
  },
  addressText: {
    fontSize: 14,
    color: "#666",
    marginBottom: 8,
    lineHeight: 20,
  },
  addressPhone: {
    fontSize: 14,
    color: "#666",
    fontWeight: "500",
  },
  itemsContainer: {
    gap: 12,
  },
  itemCard: {
    flexDirection: "row",
    backgroundColor: "white",
    padding: 16,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    alignItems: "flex-start",
  },
  itemImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 12,
  },
  itemDetails: {
    flex: 1,
  },
  itemName: {
    fontSize: 16,
    fontWeight: "500",
    color: "#1a1a1a",
    marginBottom: 4,
  },
  itemPrice: {
    fontSize: 12,
    color: "#666",
    marginBottom: 2,
  },
  itemTotalPrice: {
    fontSize: 13,
    fontWeight: "600",
    color: "#2F855A",
    marginBottom: 2,
  },
  variantText: {
    fontSize: 12,
    color: "#888",
    fontStyle: "italic",
    marginBottom: 2,
  },
  customizationsText: {
    fontSize: 12,
    color: "#666",
  },
  outOfStock: {
    color: "#e74c3c",
    fontWeight: "500",
  },
  itemPriceContainer: {
    alignItems: "flex-end",
    justifyContent: "center",
  },
  // ✅ Quantity control styles
  quantityControls: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f8f9fa",
    borderRadius: 8,
    padding: 4,
    color: "red",
    borderWidth: 0.3,
    borderColor: "red",
  },
  quantityButton: {
    width: 22,
    height: 25,
    borderRadius: 6,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
  },
  quantityButtonDisabled: {
    backgroundColor: "#f5f5f5",
    borderColor: "#f0f0f0",
  },
  quantityText: {
    fontSize: 14,
    fontWeight: "600",
    color: "red",
    marginHorizontal: 9,
    minWidth: 20,
    textAlign: "center",
  },
  fulfillmentContainer: {
    gap: 12,
  },
  fulfillmentOption: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#e0e0e0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  selectedFulfillment: {
    borderColor: "red",
    backgroundColor: "#f8ededff",
  },
  radio: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#e0e0e0",
    marginRight: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  radioSelected: {
    borderColor: "red",
  },
  radioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "red",
  },
  fulfillmentDetails: {
    flex: 1,
  },
  fulfillmentText: {
    fontSize: 16,
    fontWeight: "500",
    color: "#1a1a1a",
    marginBottom: 2,
  },
  fulfillmentTime: {
    fontSize: 14,
    color: "#666",
  },
  outOfStockSection: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#fff3cd",
    padding: 16,
    borderRadius: 12,
    marginVertical: 16,
    gap: 12,
    borderLeftWidth: 4,
    borderLeftColor: "#f39c12",
  },
  outOfStockContent: {
    flex: 1,
  },
  outOfStockTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#856404",
    marginBottom: 4,
  },
  outOfStockMessage: {
    fontSize: 14,
    color: "#856404",
    lineHeight: 20,
  },
});
