import {  StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#fff" },
  container: { flexGrow: 1, backgroundColor: "#fff" },
  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    marginTop: 10,
    paddingBottom: 16,
    backgroundColor: "#fff",
  },
  section: { marginHorizontal: 10, marginBottom: 20 },
  subCategories: {
    flexDirection: "row",
    marginVertical: 15,
  },
  backButton: { marginRight: 14, padding: 4, marginTop: -10,marginLeft:-10 },
  searchWrapper: { flex: 1, marginTop: -20 },
  subCategory: {
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
    width: 80,
  },
  subCategoryImage: {
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    // Remove shadows and glassy effect to match image
    shadowColor: "transparent",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
    // Remove borders
    borderWidth: 0,
    borderColor: "transparent",
    // Add background transparency
    backgroundColor: "transparent",
  },
  subCategoryIcon: {
    width: 90,
    height: 80,
    borderRadius: 20,
  },
  subHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 15,
    marginHorizontal: 10,
  },
  subHeadingTextUp: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
    textAlign: "center",
    marginTop:-5
  },
  line: {
    flex: 1,
    height: 1,
    backgroundColor: "#b61616",
    marginHorizontal: 10,
  },
  subHeadingText: {
    fontSize: 18,
    fontWeight: "600",
    color: "black",
    textAlign: "center",
  },
  viewMoreButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 4,
    paddingHorizontal: 5,
    borderRadius: 20,
    alignSelf: "flex-end",
    borderWidth: 1,
    borderColor: "#ddd",
    marginTop: -10,
    marginBottom: -15,
  },
  viewMoreButtonText: { color: "#F13A3A", fontSize: 12, fontWeight: "500" },
  noStoresContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
    paddingHorizontal: 20,
    minHeight: 120,
  },
  animatedContent: { alignItems: "center", justifyContent: "center" },
  animatedText: {
    fontSize: 16,
    color: "#555",
    marginTop: 12,
    textAlign: "center",
    fontWeight: "500",
  },
  subCategoryName: {
    fontSize: 12,
    fontWeight: "400",
    color: "#333",
    textAlign: "center",
  },
  offersContainer: {
    height: 200,
    marginVertical: 15,
    paddingHorizontal: 5,
  },
  noRestaurantsContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
    paddingHorizontal: 20,
    minHeight: 120,
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  errorText: {
    color: "#DC2626",
    fontSize: 16,
    textAlign: "center",
    marginBottom: 16,
    fontWeight: "500",
  },
});