import { Dimensions, StyleSheet } from "react-native";
const windowWidth = Dimensions.get("window").width;
export const styles = StyleSheet.create({
  // ✅ New compact restaurant card styles (similar to store card size)
  restaurantCardCompact: {
    backgroundColor: "white",
    borderRadius: 12,
    marginRight: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    width: 200, // Same as nearbyCard width
    overflow: "hidden",
  },
    topActions: {
    position: "absolute",
    top: 12,
    right: 12,
    flexDirection: "row",
    gap: 8,
    backgroundColor: "rgba(255,255,255,0.9)",
    borderRadius: 20,
    padding: 6,
    elevation: 3,
  },
  restaurantImageContainerCompact: {
    position: "relative",
    width: "100%",
    height: 120, // Same as nearbyImage height
    backgroundColor: "#f5f5f5",
  },
  restaurantImageCompact: {
    width: "100%",
    height: "100%",
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  // ✅ Linear gradient overlay for restaurants
  gradientOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  restaurantOfferBadgeCompact: {
    position: "absolute",
    top: 8,
    left: 8,
    backgroundColor: "#FF6B35",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    zIndex: 1,
  },
  restaurantOfferTextCompact: {
    color: "white",
    fontSize: 10,
    fontWeight: "600",
  },
  restaurantTimeBadgeCompact: {
    position: "absolute",
    bottom: 8,
    right: 8,
    backgroundColor: "rgba(0,0,0,0.7)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    zIndex: 1,
  },
  restaurantTimeTextCompact: {
    color: "white",
    fontSize: 10,
    marginLeft: 2,
    fontWeight: "500",
  },
  restaurantInfoCompact: {
    padding: 12, // Same as nearbyInfo padding
  },
  restaurantNameCompact: {
    fontSize: 16, // Same as nearbyName
    fontWeight: "600",
    color: "#333",
    marginBottom: 4,
  },
  restaurantCuisineCompact: {
    fontSize: 12, // Same as nearbyCategory
    color: "#888",
    marginBottom: 8,
    textTransform: "capitalize",
  },
  restaurantBottomRowCompact: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  restaurantDeliveryTimeCompact: {
    fontSize: 12,
    color: "#FF9130", // Orange color like nearbyDistance
    fontWeight: "500",
  },
  restaurantStatusCompact: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 8,
    marginBottom: 4
  },
  restaurantStatusDotCompact: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: 4,
  },
  restaurantStatusTextCompact: {
    fontSize: 12,
    fontWeight: "600",
  },

  // Original restaurant card styles (keeping for backward compatibility)
  restaurantCard: {
    backgroundColor: "white",
    borderRadius: 16,
    marginRight: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
    width: 200,
    overflow: "hidden",
  },
  restaurantImageContainer: {
    position: "relative",
    width: "100%",
    height: 140,
    backgroundColor: "#f8f8f8",
  },
  restaurantImage: {
    width: "100%",
    height: "100%",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  restaurantOfferBadge: {
    position: "absolute",
    top: 10,
    left: 10,
    backgroundColor: "#FF6B35",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
  },
  restaurantOfferText: {
    color: "white",
    fontSize: 11,
    fontWeight: "700",
  },
  restaurantTimeBadge: {
    position: "absolute",
    bottom: 10,
    right: 10,
    backgroundColor: "rgba(0,0,0,0.8)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  restaurantTimeText: {
    color: "white",
    fontSize: 11,
    marginLeft: 3,
    fontWeight: "600",
  },
  restaurantInfo: {
    padding: 14,
  },
  restaurantName: {
    fontSize: 18,
    fontWeight: "700",
    color: "#2C2C2C",
    marginBottom: 4,
  },
  restaurantCuisine: {
    fontSize: 13,
    color: "#7A7A7A",
    marginBottom: 8,
    textTransform: "capitalize",
  },
  restaurantDetailsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  restaurantRating: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#00A651",
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 6,
  },
  restaurantRatingText: {
    fontSize: 13,
    color: "white",
    marginLeft: 3,
    fontWeight: "600",
  },
  restaurantDeliveryTime: {
    fontSize: 13,
    color: "#666",
    fontWeight: "500",
  },
  restaurantBottomRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  restaurantLocation: {
    fontSize: 12,
    color: "#8A8A8A",
    flex: 1,
    marginRight: 8,
  },
  restaurantStatus: {
    flexDirection: "row",
    alignItems: "center",
  },
  restaurantStatusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    marginRight: 5,
  },
  restaurantStatusText: {
    fontSize: 12,
    fontWeight: "600",
  },

  // Store card styles (unchanged)
  nearbyCard: {
    backgroundColor: "white",
    borderRadius: 12,
    marginRight: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    width: 200,
    overflow: "hidden",
  },
  nearbyImageContainer: {
    position: "relative",
    width: "100%",
    height: 120,
    backgroundColor: "#f5f5f5",
  },
  nearbyImage: {
    width: "100%",
    height: "100%",
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  offerBadge: {
    position: "absolute",
    top: 8,
    left: 8,
    backgroundColor: "red",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  offerBadgeText: {
    color: "white",
    fontSize: 10,
    fontWeight: "600",
  },
  nearbyInfo: {
    padding: 12,
  },
  nearbyName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    marginBottom: 4,
  },
  nearbyCategory: {
    fontSize: 12,
    color: "#888",
    marginBottom: 4,
    textTransform: "capitalize",
  },
  nearbyDistance: {
    fontSize: 12,
    color: "#FF9130",
    fontWeight: "500",
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  ratingText: {
    fontSize: 12,
    color: "#666",
    marginLeft: 4,
  },
  categoryRow: {
    margin: 5,
    flexDirection: "column",
    alignItems: "center",
  },
  categoryItem: {
    margin: 5,
    flexDirection: "column",
    alignItems: "center",
  },
  categoryImage: {
    width: windowWidth * 0.2,
    height: windowWidth * 0.24,
    resizeMode: "contain",
  },
  categoryName: {
    marginTop: -9,
    color: "black",
    fontSize: 12,
    fontWeight: "bold",
    textAlign: "center",
  },
  catCard: {
    alignItems: "center",
    justifyContent: "center",
    marginRight: 18,
    width: 46,
    borderRadius: 8,
    backgroundColor: "transparent",
    paddingVertical: 8,
  },
  imageContainer: {
    marginBottom: 6,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
    borderRadius: 20,
  },
  iconImg: {
    width: 45,
    height: 40,
    resizeMode: "contain",
    borderRadius: 8,
  },
  catLabel: {
    color: "white",
    fontSize: 12,
    textAlign: "center",
    fontWeight: "600",
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },

  // Compact version styles
  catCardCompact: {
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
    width: 50,
    borderRadius: 8,
    backgroundColor: "transparent",
    paddingVertical: 6,
  },
  iconImgCompact: {
    width: 40,
    height: 36,
    resizeMode: "contain",
    borderRadius: 6,
    marginBottom: 2,
  },
  catLabelCompact: {
    color: "white",
    fontSize: 10,
    textAlign: "center",
    fontWeight: "bold",
    textShadowColor: 'rgba(0, 0, 0, 0.4)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
    marginBottom: -7
  },
});