import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  header: { flexDirection: 'row', alignItems: 'center', padding: 16, borderBottomWidth: 1, borderColor: '#eee' },
  closeButton: { marginRight: 12 },
  headerContent: { flex: 1 },
  productName: { fontSize: 16, fontWeight: '600' },
  headerTitle: { fontSize: 14, color: '#666' },
  scrollContainer: { flex: 1, padding: 16 },
  backButton: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  backButtonText: { marginLeft: 4, color: '#f14343', fontWeight: '500' },
  groupContainer: { marginBottom: 16 },
  groupHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  groupTitleContainer: { flexDirection: 'row', alignItems: 'center' },
  groupTitle: { fontSize: 16, fontWeight: '500' },
  required: { color: '#f14343' },
  clearButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#f14343', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 4, marginLeft: 8 },
  clearButtonText: { color: '#fff', marginRight: 4 },
  groupSubtitle: { fontSize: 12, color: '#999' },
  optionsContainer: {},
  optionContainer: { flexDirection: 'row', justifyContent: 'space-between', padding: 12, borderWidth: 1, borderColor: '#eee', borderRadius: 8, marginBottom: 8 },
  optionContent: { flexDirection: 'row', justifyContent: 'space-between', flex: 1 },
  optionLeft: { flexDirection: 'row', alignItems: 'center' },
  optionName: { marginLeft: 8 },
  optionRight: { flexDirection: 'row', alignItems: 'center' },
  optionPrice: { marginRight: 8, fontWeight: '500' },
  selectionIndicator: {},
  checkbox: { width: 20, height: 20, borderWidth: 1, borderColor: '#999', justifyContent: 'center', alignItems: 'center', borderRadius: 4 },
  checkboxSelected: { backgroundColor: '#f14343', borderColor: '#f14343' },
  radio: { width: 20, height: 20, borderWidth: 1, borderColor: '#999', borderRadius: 10, justifyContent: 'center', alignItems: 'center' },
  radioSelected: { borderColor: '#f14343' },
  radioDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#f14343' },
  dietIcon: { width: 14, height: 14, borderWidth: 1, borderRadius: 2, justifyContent: 'center', alignItems: 'center' },
  dietDot: { width: 8, height: 8, borderRadius: 4 },
  optionSelected: { borderColor: '#f14343' },
  optionDisabled: { opacity: 0.6 },
  disabledText: { color: '#999' },
  continueButton: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', backgroundColor: '#f14343', padding: 12, borderRadius: 8, marginVertical: 16 },
  continueButtonDisabled: { backgroundColor: '#ccc' },
  continueButtonText: { color: '#fff', fontWeight: '600', marginRight: 4 },
  continueButtonTextDisabled: { color: '#999' },
  footer: { padding: 16, borderTopWidth: 1, borderColor: '#eee' },
  selectedText: { fontSize: 14, color: '#666', marginBottom: 8 },
  totalPrice: { fontSize: 16, fontWeight: '600', marginBottom: 8 },
  updateCartButton: { backgroundColor: '#f14343', padding: 14, borderRadius: 8, alignItems: 'center' },
  updateCartButtonDisabled: { backgroundColor: '#ccc' },
  updateCartButtonText: { color: '#fff', fontWeight: '600', fontSize: 16 },
  loadingContainer: { flexDirection: 'row', alignItems: 'center' },
  loadingText: { color: '#fff', marginLeft: 8 },
});